title: Platform.AI
author: Arshak Navruzyan
email: arshak@platform.ai
description: >-
  Platform allows domain experts to produce high-quality labels for AI applications in minutes in a visual, interactive fashion.  
  It combines the latest research in human perception, active learning, transfer from pre-trained nets, 
  and noise-resilient training so that the labeler's time is used in the most productive way and the model learns from every 
  aspect of the human interaction.
baseurl: "/ubuild-jekyll" # the subpath of your site, e.g. /blog
url: "" # your site's origin, e.g. https://forestry.io

# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-menus
  

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
